@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4OTU1YTJmZS0xMDZiLTQwYTktYmFjZC0wNGZhNTg5MmI1NjEiLCJpYXQiOjE3NDc1OTgxMzIsImV4cCI6MTc0ODIwMjkzMn0.jjEWj7-QGinw5a-8LA8CPe17ZPHCtyXrgCrCBGWA8so

### Create Org
POST http://localhost:3333/orgs
Content-Type: application/json

{
  "responsibleName": "John Doe",
  "email": "oM8t4@example.com",
  "zipCode": "12345",
  "address": "123 Main St",
  "neighborhood": "Downtown",
  "stateCode": "SP",
  "IBGECityCode": "12345",
  "whatsapp": "123456789",
  "password": "123456"
}

### Authenticate
POST http://localhost:3333/auth/login
Content-Type: application/json

{
  "email": "oM8t4@example.com",
  "password": "123456"
}

### Create Pet
POST http://localhost:3333/pets
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Fido 10",
  "about": "A good dog",
  "size": "SMALL",
  "type": "DOG",
  "lifeStage": "ADULT",
  "idealEnvironment": "INDOOR",
  "energyLevel": "HIGH",
  "independenceLevel": "LOW",
  "requirements": [
    {
      "description": "Good behavior"
    },
    {
      "description": "Good health"
    }
  ]
}

### Fetch Pets
GET http://localhost:3333/pets?cityCode=12345&stateCode=SP&page=2&perPage=2&type=DOG
Authorization: {{token}}

### Pet Details
GET http://localhost:3333/pets/86791418-2db0-4a72-808f-58e17b3dfec2
Authorization: {{token}}